import { createServerSupabaseAdmin } from "@/lib/supabase/server";
import { calculateLeadScore, type LeadScoreComponents } from "./lead-score";
export type VerifiedLeadCandidate={companyId:string;name:string;sourceType:string;sourceUrl:string;website?:string|null;email?:string|null;phone?:string|null;language?:string|null;externalId?:string|null;confidence:number;scoreComponents:LeadScoreComponents;problemDetected?:string|null;recommendedOffer?:string|null;bestChannel?:string|null;enrichment?:Array<{field:string;value:unknown;sourceUrl:string;confidence:number}>};
const norm=(v?:string|null)=>v?.trim().toLowerCase()||null;
export async function ingestVerifiedLead(c:VerifiedLeadCandidate){
 if(!c.sourceUrl?.trim())throw new Error("A source URL is required; unverified leads cannot be ingested");const db=createServerSupabaseAdmin();const email=norm(c.email),phone=norm(c.phone),website=norm(c.website);let existingId:string|null=null;
 if(c.externalId){const {data}=await db.from("lead_sources").select("lead_id").eq("company_id",c.companyId).eq("source_type",c.sourceType).eq("external_id",c.externalId).maybeSingle();existingId=data?.lead_id??null}
 if(!existingId&&(email||phone)){const {data:contacts}=await db.from("contacts").select("id,email,phone").eq("company_id",c.companyId).limit(250);const contact=(contacts??[]).find(r=>(email&&norm(r.email)===email)||(phone&&norm(r.phone)===phone));if(contact){const {data:lead}=await db.from("leads").select("id").eq("company_id",c.companyId).eq("contact_id",contact.id).maybeSingle();existingId=lead?.id??null}}
 if(!existingId&&website){const {data}=await db.from("lead_enrichment").select("lead_id,field_value").eq("company_id",c.companyId).eq("field_name","website").limit(250);existingId=(data??[]).find(r=>norm(typeof r.field_value==="string"?r.field_value:null)===website)?.lead_id??null}
 if(existingId)return{leadId:existingId,duplicate:true};
 const {data:contact,error:contactError}=await db.from("contacts").insert({company_id:c.companyId,first_name:c.name,email,phone,company:c.name,status:"lead"}).select("id").single();if(contactError)throw contactError;
 const score=calculateLeadScore(c.scoreComponents,c);const {data:lead,error:leadError}=await db.from("leads").insert({company_id:c.companyId,contact_id:contact.id,source:c.sourceType,score:score.score,revenue_stage:score.score>=50?"qualified":"researched",score_reason:score.components,opportunity_summary:c.problemDetected??null,recommended_offer:c.recommendedOffer??null,best_channel:c.bestChannel??null,next_best_action:score.nextBestAction,language:c.language??null,confidence:Math.max(0,Math.min(1,c.confidence))}).select("id").single();if(leadError)throw leadError;
 const {error:sourceError}=await db.from("lead_sources").insert({company_id:c.companyId,lead_id:lead.id,source_type:c.sourceType,source_url:c.sourceUrl,external_id:c.externalId??null});if(sourceError)throw sourceError;
 const {error:scoreError}=await db.from("lead_scores").insert({company_id:c.companyId,lead_id:lead.id,score:score.score,components:score.components,explanation:score.explanation.join(" · "),problem_detected:score.problemDetected,recommended_offer:score.recommendedOffer,best_channel:score.bestChannel,next_best_action:score.nextBestAction});if(scoreError)throw scoreError;
 const enrichment=[...(c.enrichment??[]),...(website?[{field:"website",value:c.website,sourceUrl:c.sourceUrl,confidence:c.confidence}]:[])];if(enrichment.length){const {error}=await db.from("lead_enrichment").insert(enrichment.map(i=>({company_id:c.companyId,lead_id:lead.id,field_name:i.field,field_value:i.value,source_url:i.sourceUrl,confidence:Math.max(0,Math.min(1,i.confidence)),verified_at:new Date().toISOString()})));if(error)throw error}return{leadId:lead.id,duplicate:false,score};
}
