import type { ExecutiveWatcher, WatcherSignal } from "../types/watcher.types";

const NOW = new Date().toISOString();

function signal(
  watcherId: string,
  category: ExecutiveWatcher["category"],
  metric: string,
  value: number,
  threshold: number,
  direction: WatcherSignal["direction"],
): WatcherSignal {
  return {
    id: `signal-${watcherId}-${metric}`,
    watcherId,
    category,
    metric,
    value,
    threshold,
    direction,
    source: "internal",
    detectedAt: NOW,
  };
}

export const WATCHER_CATEGORIES = [
  "market",
  "seo",
  "reputation",
  "campaign",
  "finance",
  "sales",
  "operations",
  "legal",
  "hr",
  "technology",
] as const;

export const CATEGORY_LABELS: Record<
  (typeof WATCHER_CATEGORIES)[number],
  string
> = {
  market: "Mercado",
  seo: "SEO",
  reputation: "Reputação",
  campaign: "Campanhas",
  finance: "Financeiro",
  sales: "Vendas",
  operations: "Operações",
  legal: "Jurídico",
  hr: "RH",
  technology: "Tecnologia",
};

export const MOCK_EXECUTIVE_WATCHERS: ExecutiveWatcher[] = [
  {
    id: "watcher-market-trends",
    name: "Market Trends Monitor",
    description: "Monitora movimentos de mercado e pressão competitiva.",
    category: "market",
    severity: "high",
    frequency: "daily",
    status: "active",
    source: "external",
    responsibleArea: "Strategy",
    lastRunAt: NOW,
    nextRunAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    signals: [
      signal("watcher-market-trends", "market", "competitor_activity_index", 78, 65, "above"),
    ],
  },
  {
    id: "watcher-seo-health",
    name: "SEO Health Monitor",
    description: "Acompanha quedas de tráfego orgânico e indexação.",
    category: "seo",
    severity: "medium",
    frequency: "daily",
    status: "triggered",
    source: "integration",
    responsibleArea: "Marketing",
    lastRunAt: NOW,
    nextRunAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    signals: [
      signal("watcher-seo-health", "seo", "organic_traffic_change_percent", -12, -8, "below"),
    ],
  },
  {
    id: "watcher-reputation",
    name: "Reputation Monitor",
    description: "Detecta variações em reviews e menções de marca.",
    category: "reputation",
    severity: "high",
    frequency: "hourly",
    status: "active",
    source: "integration",
    responsibleArea: "Marketing",
    lastRunAt: NOW,
    nextRunAt: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    signals: [
      signal("watcher-reputation", "reputation", "unanswered_reviews", 8, 5, "above"),
    ],
  },
  {
    id: "watcher-campaign-performance",
    name: "Campaign Performance Monitor",
    description: "Monitora ROAS, CTR e gasto de campanhas pagas.",
    category: "campaign",
    severity: "medium",
    frequency: "hourly",
    status: "active",
    source: "integration",
    responsibleArea: "Marketing",
    lastRunAt: NOW,
    nextRunAt: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    signals: [
      signal("watcher-campaign-performance", "campaign", "roas", 2.1, 2.5, "below"),
    ],
  },
  {
    id: "watcher-finance-cashflow",
    name: "Cash Flow Monitor",
    description: "Acompanha margem, burn rate e saúde financeira.",
    category: "finance",
    severity: "critical",
    frequency: "daily",
    status: "triggered",
    source: "internal",
    responsibleArea: "Finance",
    lastRunAt: NOW,
    nextRunAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    signals: [
      signal("watcher-finance-cashflow", "finance", "cash_runway_months", 4.2, 6, "below"),
    ],
  },
  {
    id: "watcher-sales-pipeline",
    name: "Sales Pipeline Monitor",
    description: "Monitora conversão, win rate e pipeline estagnado.",
    category: "sales",
    severity: "medium",
    frequency: "daily",
    status: "active",
    source: "internal",
    responsibleArea: "Sales",
    lastRunAt: NOW,
    signals: [
      signal("watcher-sales-pipeline", "sales", "stalled_deals", 14, 10, "above"),
    ],
  },
  {
    id: "watcher-operations-sla",
    name: "Operations SLA Monitor",
    description: "Acompanha atrasos operacionais e produtividade.",
    category: "operations",
    severity: "low",
    frequency: "daily",
    status: "active",
    source: "internal",
    responsibleArea: "Operations",
    lastRunAt: NOW,
    signals: [
      signal("watcher-operations-sla", "operations", "delay_risk_percent", 22, 25, "below"),
    ],
  },
  {
    id: "watcher-legal-compliance",
    name: "Compliance Monitor",
    description: "Monitora riscos regulatórios e pendências jurídicas.",
    category: "legal",
    severity: "high",
    frequency: "weekly",
    status: "active",
    source: "internal",
    responsibleArea: "Legal",
    lastRunAt: NOW,
    signals: [
      signal("watcher-legal-compliance", "legal", "open_compliance_items", 3, 2, "above"),
    ],
  },
  {
    id: "watcher-hr-engagement",
    name: "HR Engagement Monitor",
    description: "Acompanha engajamento e risco de turnover.",
    category: "hr",
    severity: "medium",
    frequency: "weekly",
    status: "active",
    source: "internal",
    responsibleArea: "HR",
    lastRunAt: NOW,
    signals: [
      signal("watcher-hr-engagement", "hr", "engagement_score", 58, 65, "below"),
    ],
  },
  {
    id: "watcher-technology-uptime",
    name: "Technology Uptime Monitor",
    description: "Monitora disponibilidade e incidentes tecnológicos.",
    category: "technology",
    severity: "high",
    frequency: "realtime",
    status: "active",
    source: "external",
    responsibleArea: "Technology",
    lastRunAt: NOW,
    nextRunAt: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
    signals: [
      signal("watcher-technology-uptime", "technology", "error_rate_percent", 1.8, 1.2, "above"),
    ],
  },
];
