export * from "./opportunity-repository.port";
export * from "./opportunity-detector.port";
export * from "./roi-analyzer.port";
export * from "./priority-calculator.port";
export * from "./risk-analyzer.port";
export * from "./recommendation-builder.port";
export * from "./execution-planner.port";
export * from "./impact-analyzer.port";
export * from "./executive-opportunity-engine.port";
