import type { SamuelCapabilityDefinition } from "./samuel-capability.types";

export const SAMUEL_CAPABILITIES: SamuelCapabilityDefinition[] = [
  {
    id: "research.company",
    title: "Research Company",
    description: "Pesquisa uma empresa usando o executor de análise já conectado e preserva evidências de origem.",
    domain: "research",
    availability: "connected",
    executionClass: "read",
    minimumAutonomy: 0,
    requiresApproval: false,
    evidencePolicy: "source",
    executor: { kind: "server_route", endpoint: "/api/company/analyze", method: "POST" },
    timeoutMs: 45_000,
    cancellable: true,
    voiceEnabled: true,
    requirements: [],
  },
  {
    id: "workspace.email",
    title: "Email Operations",
    description: "Executa ações de email através do Samuel Action Engine, com confirmação, idempotência e ledger.",
    domain: "workspace",
    availability: "connected",
    executionClass: "mutate",
    minimumAutonomy: 1,
    requiresApproval: true,
    evidencePolicy: "ledger",
    executor: { kind: "action_engine", subject: "gmail" },
    timeoutMs: 45_000,
    cancellable: true,
    voiceEnabled: true,
    requirements: ["connected_gmail_account"],
  },
  {
    id: "workspace.calendar",
    title: "Calendar Operations",
    description: "Cria, altera e remove eventos através do Samuel Action Engine com trilha de execução.",
    domain: "workspace",
    availability: "connected",
    executionClass: "mutate",
    minimumAutonomy: 1,
    requiresApproval: true,
    evidencePolicy: "ledger",
    executor: { kind: "action_engine", subject: "calendar" },
    timeoutMs: 45_000,
    cancellable: true,
    voiceEnabled: true,
    requirements: ["connected_google_calendar"],
  },
  {
    id: "workspace.drive",
    title: "Drive Operations",
    description: "Cria, organiza e compartilha conteúdo no Drive através do Samuel Action Engine.",
    domain: "workspace",
    availability: "connected",
    executionClass: "mutate",
    minimumAutonomy: 1,
    requiresApproval: true,
    evidencePolicy: "ledger",
    executor: { kind: "action_engine", subject: "drive" },
    timeoutMs: 45_000,
    cancellable: true,
    voiceEnabled: true,
    requirements: ["connected_google_drive"],
  },
  {
    id: "desktop.computer",
    title: "Supervised Computer Use",
    description: "Opera o Windows pareado por captura de tela, ação, nova observação e evidência visual.",
    domain: "desktop",
    availability: "connected",
    executionClass: "sensitive",
    minimumAutonomy: 1,
    requiresApproval: true,
    evidencePolicy: "visual",
    executor: { kind: "desktop", action: "computer.task" },
    timeoutMs: 120_000,
    cancellable: true,
    voiceEnabled: true,
    requirements: ["paired_samuel_desktop"],
  },
  {
    id: "growth.lead-discovery",
    title: "Lead Discovery",
    description: "Descobre empresas e preserva proveniência antes de inserir leads no fluxo comercial.",
    domain: "growth",
    availability: "planned",
    executionClass: "read",
    minimumAutonomy: 0,
    requiresApproval: false,
    evidencePolicy: "source",
    executor: null,
    timeoutMs: 60_000,
    cancellable: true,
    voiceEnabled: false,
    requirements: ["verified_lead_discovery_executor"],
  },
  {
    id: "growth.website-audit",
    title: "Website Audit",
    description: "Audita presença digital, mobile, conversão, conteúdo e oportunidades com evidências verificáveis.",
    domain: "growth",
    availability: "planned",
    executionClass: "read",
    minimumAutonomy: 0,
    requiresApproval: false,
    evidencePolicy: "source",
    executor: null,
    timeoutMs: 60_000,
    cancellable: true,
    voiceEnabled: false,
    requirements: ["verified_website_audit_executor"],
  },
  {
    id: "growth.ads-analysis",
    title: "Ads Analysis",
    description: "Analisa campanhas conectadas e produz recomendações explicáveis sem alterar investimento automaticamente.",
    domain: "growth",
    availability: "planned",
    executionClass: "read",
    minimumAutonomy: 0,
    requiresApproval: false,
    evidencePolicy: "source",
    executor: null,
    timeoutMs: 60_000,
    cancellable: true,
    voiceEnabled: false,
    requirements: ["verified_ads_connector_executor"],
  },
  {
    id: "creative.website",
    title: "Premium Website Creation",
    description: "Cria e valida experiências web premium usando o Studio e quality gates do projeto.",
    domain: "creative",
    availability: "planned",
    executionClass: "draft",
    minimumAutonomy: 1,
    requiresApproval: true,
    evidencePolicy: "artifact",
    executor: null,
    timeoutMs: 180_000,
    cancellable: true,
    voiceEnabled: false,
    requirements: ["verified_studio_execution_adapter"],
  },
  {
    id: "sales.proposal",
    title: "Sales Proposal",
    description: "Produz proposta comercial vinculada a dados reais, oferta cadastrada e trilha de aprovação.",
    domain: "sales",
    availability: "planned",
    executionClass: "draft",
    minimumAutonomy: 1,
    requiresApproval: true,
    evidencePolicy: "artifact",
    executor: null,
    timeoutMs: 60_000,
    cancellable: true,
    voiceEnabled: false,
    requirements: ["verified_proposal_executor"],
  },
  {
    id: "sales.outreach",
    title: "Sales Outreach",
    description: "Prepara abordagem comercial baseada em evidências do lead e separa rascunho de envio real.",
    domain: "sales",
    availability: "planned",
    executionClass: "draft",
    minimumAutonomy: 1,
    requiresApproval: true,
    evidencePolicy: "artifact",
    executor: null,
    timeoutMs: 60_000,
    cancellable: true,
    voiceEnabled: false,
    requirements: ["verified_outreach_executor"],
  },
  {
    id: "sales.crm",
    title: "CRM Operations",
    description: "Atualiza estágio, tarefas e próxima ação preservando isolamento por empresa e trilha de auditoria.",
    domain: "sales",
    availability: "planned",
    executionClass: "mutate",
    minimumAutonomy: 1,
    requiresApproval: false,
    evidencePolicy: "ledger",
    executor: null,
    timeoutMs: 45_000,
    cancellable: true,
    voiceEnabled: false,
    requirements: ["verified_crm_executor"],
  },
  {
    id: "creative.vector",
    title: "Editable Vector Creation",
    description: "Cria arte vetorial realmente editável, com saída SVG/Figma/Canva em vez de raster disfarçado de vetor.",
    domain: "creative",
    availability: "planned",
    executionClass: "draft",
    minimumAutonomy: 1,
    requiresApproval: true,
    evidencePolicy: "artifact",
    executor: null,
    timeoutMs: 180_000,
    cancellable: true,
    voiceEnabled: false,
    requirements: ["vector_provider", "editable_artifact_pipeline", "quality_gate"],
  },
  {
    id: "creative.image",
    title: "Image Creation",
    description: "Gera e revisa imagens raster com versionamento, briefing e quality gate antes da entrega.",
    domain: "creative",
    availability: "planned",
    executionClass: "draft",
    minimumAutonomy: 1,
    requiresApproval: true,
    evidencePolicy: "artifact",
    executor: null,
    timeoutMs: 180_000,
    cancellable: true,
    voiceEnabled: false,
    requirements: ["image_provider", "asset_storage", "quality_gate"],
  },
  {
    id: "creative.video",
    title: "Video Creation",
    description: "Orquestra criação de vídeo como job verificável, com revisão e artefato final rastreável.",
    domain: "creative",
    availability: "planned",
    executionClass: "draft",
    minimumAutonomy: 1,
    requiresApproval: true,
    evidencePolicy: "artifact",
    executor: null,
    timeoutMs: 600_000,
    cancellable: true,
    voiceEnabled: false,
    requirements: ["video_provider", "job_lifecycle", "asset_storage", "quality_gate"],
  },
  {
    id: "social.publish",
    title: "Social Publishing",
    description: "Publica conteúdo por APIs oficiais e só declara sucesso quando existe recibo ou ID da plataforma.",
    domain: "social",
    availability: "planned",
    executionClass: "mutate",
    minimumAutonomy: 2,
    requiresApproval: true,
    evidencePolicy: "platform_receipt",
    executor: null,
    timeoutMs: 120_000,
    cancellable: true,
    voiceEnabled: false,
    requirements: ["platform_oauth", "official_publish_api", "scheduler", "platform_receipt_verification"],
  },
];

export function getSamuelCapability(id: string) {
  return SAMUEL_CAPABILITIES.find((capability) => capability.id === id) ?? null;
}

export function listSamuelCapabilities(options?: {
  availability?: SamuelCapabilityDefinition["availability"];
  domain?: SamuelCapabilityDefinition["domain"];
  voiceEnabled?: boolean;
}) {
  return SAMUEL_CAPABILITIES.filter((capability) => {
    if (options?.availability && capability.availability !== options.availability) return false;
    if (options?.domain && capability.domain !== options.domain) return false;
    if (typeof options?.voiceEnabled === "boolean" && capability.voiceEnabled !== options.voiceEnabled) return false;
    return true;
  });
}
