const SUPABASE_URL='https://nuvkkystobhzdszmggfm.supabase.co';
const SUPABASE_KEY='sb_publishable_ieR5LfgjSJqbo4JdD2N-QA_WQJl7o46';
const FUTURE_ME_URL='https://future-me-ai-sf-growth-ai.vercel.app';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let authMode='signup',session=null,user=null,profile=null,role='user',current='dashboard',mode='strategic';
let state={goals:[],actions:[],checkins:[],vision:[],declarations:[],missions:[],messages:[],scores:null,pillars:[]};
const PKEYS=['spiritual','mental','body','financial'];
const PLABEL={spiritual:'Espiritual',mental:'Mental / emocional',body:'Corpo',financial:'Financeiro'};
const PICON={spiritual:'✦',mental:'◈',body:'✚',financial:'▥'};
const PCOLOR={spiritual:'#ffb64a',mental:'#b56dff',body:'#42d890',financial:'#46a9ff'};
const basePages=[['dashboard','Início'],['pillars','4 Pilares'],['vision','Meu Futuro'],['mentor','Mentor IA'],['plan','Plano e Metas'],['checkin','Check-in'],['review','Revisão Semanal'],['missions','Missões'],['declarations','Declarações'],['letter','Carta do Eu Futuro'],['profile','Perfil'],['plans','Planos']];
const DAILY=[
 {t:'verse',text:'Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.',ref:'Salmos 37:5'},
 {t:'quote',text:'A disciplina é a ponte entre a intenção e a transformação.',ref:'Princípio de execução'},
 {t:'verse',text:'Os planos do diligente tendem à abundância.',ref:'Provérbios 21:5'},
 {t:'quote',text:'Você não precisa controlar o futuro. Precisa governar bem a próxima decisão.',ref:'Future Me'},
 {t:'verse',text:'Sê forte e corajoso; não temas, porque o Senhor teu Deus é contigo.',ref:'Josué 1:9'},
 {t:'quote',text:'Clareza sem ação vira desejo. Ação sem direção vira desgaste. Una as duas.',ref:'Future Me'},
 {t:'verse',text:'Tudo posso naquele que me fortalece.',ref:'Filipenses 4:13'},
 {t:'quote',text:'O que você repete em silêncio torna-se visível nos seus resultados.',ref:'Future Me'},
 {t:'verse',text:'Tudo quanto te vier à mão para fazer, faze-o conforme as tuas forças.',ref:'Eclesiastes 9:10'},
 {t:'quote',text:'Não negocie com a versão de você que sempre adia aquilo que importa.',ref:'Future Me'}
];
function pages(){return role==='admin'||role==='superadmin'?[...basePages,['admin','Superadmin']]:basePages}
function $id(x){return document.getElementById(x)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function todayContent(){const d=new Date();const n=Math.floor(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/86400000);return DAILY[n%DAILY.length]}
function holoHTML(score=0,clickable=true){return `<div class="holo ${clickable?'':'static'}"><div class="glow"></div><div class="coreFigure"></div>${PKEYS.map(p=>`<button class="orbit ${p}" ${clickable?`onclick="openPillar('${p}')"`:'disabled'}><span><b>${PICON[p]}</b>${PLABEL[p]}</span></button>`).join('')}<div class="holoBase"></div><div class="holoScore">Future Score ${score}/100</div></div>`}
function openPillar(p){sessionStorage.setItem('fm_pillar',p);go('pillars')}
function showAuth(m){authMode=m;landing.style.display='none';app.style.display='none';auth.style.display='flex';paintAuth()}
function backLanding(){auth.style.display='none';landing.style.display='block'}
function toggleAuth(){authMode=authMode==='signup'?'login':'signup';paintAuth()}
function paintAuth(){const sign=authMode==='signup';$id('nameLabel').classList.toggle('hidden',!sign);$id('authTitle').textContent=sign?'Criar conta':'Entrar';$id('authEy').textContent=sign?'Comece a construir':'Bem-vindo de volta';$id('authSubmit').textContent=sign?'Criar conta':'Entrar';$id('authSwitch').textContent=sign?'Já tenho conta':'Criar nova conta';$id('authMsg').classList.add('hidden')}
async function submitAuth(){const email=$id('authEmail').value.trim(),password=$id('authPassword').value,name=$id('authName').value.trim(),box=$id('authMsg');box.className='notice muted';box.textContent='A processar…';try{if(authMode==='signup'){const{data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name,future_me:true}}});if(error)throw error;const existing=!!(data.user&&Array.isArray(data.user.identities)&&data.user.identities.length===0);if(existing){authMode='login';paintAuth();$id('authEmail').value=email;box.className='notice bad';box.textContent='Este email já possui uma conta. Entre com a palavra-passe existente.';box.classList.remove('hidden');return}let s=data.session;if(!s){const login=await sb.auth.signInWithPassword({email,password});if(login.error)throw login.error;s=login.data.session}if(s){await boot(s);go('profile')}else throw new Error('Conta criada, mas a sessão não foi iniciada. Tente entrar.')}else{const{data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;await boot(data.session)}}catch(e){box.className='notice bad';box.textContent=e.message||String(e)}}
async function logout(){await sb.auth.signOut();session=user=profile=null;app.style.display='none';landing.style.display='block'}
async function ensureFutureMeIdentity(){const uid=user.id;const{data:pr}=await sb.from('future_me_profiles').select('user_id').eq('user_id',uid).maybeSingle();if(!pr)await sb.from('future_me_profiles').insert({user_id:uid,display_name:user.user_metadata?.display_name||''});const{data:rr}=await sb.from('future_me_roles').select('role').eq('user_id',uid).maybeSingle();if(!rr)await sb.from('future_me_roles').insert({user_id:uid,role:'user'})}
async function boot(s){session=s;user=s?.user;if(!user)return;await ensureFutureMeIdentity();auth.style.display='none';landing.style.display='none';app.style.display='block';await loadAll();$id('who').textContent=profile?.display_name?`Olá, ${profile.display_name}`:(user.email||'Conta ativa');renderMenu();go(location.hash.slice(1)||'dashboard')}
async function loadAll(){const uid=user.id;const [pr,rr,goals,actions,checkins,vision,declarations,missions,messages,pillars]=await Promise.all([sb.from('future_me_profiles').select('*').eq('user_id',uid).maybeSingle(),sb.from('future_me_roles').select('role').eq('user_id',uid).maybeSingle(),sb.from('future_me_goals').select('*').eq('user_id',uid).order('created_at',{ascending:false}),sb.from('future_me_actions').select('*').eq('user_id',uid).order('created_at',{ascending:false}),sb.from('future_me_checkins').select('*').eq('user_id',uid).order('checkin_date',{ascending:false}).limit(28),sb.from('future_me_vision_items').select('*').eq('user_id',uid).order('created_at',{ascending:false}),sb.from('future_me_declarations').select('*').eq('user_id',uid).order('created_at',{ascending:false}),sb.from('future_me_missions').select('*').eq('user_id',uid).order('created_at',{ascending:false}),sb.from('future_me_mentor_messages').select('*').eq('user_id',uid).order('created_at',{ascending:true}).limit(80),sb.from('future_me_pillar_profiles').select('*').eq('user_id',uid)]);profile=pr.data||{user_id:uid,display_name:user.user_metadata?.display_name||'',country:'Portugal',language:'pt',horizon_years:5,vision_text:'',obstacles:'',resources:'',first_commitment:'',consent_sensitive:false,xp:0};role=rr.data?.role||'user';state.goals=goals.data||[];state.actions=actions.data||[];state.checkins=checkins.data||[];state.vision=vision.data||[];state.declarations=declarations.data||[];state.missions=missions.data||[];state.messages=messages.data||[];state.pillars=pillars.data||[];state.scores=computeScores();await saveScore()}
function computeScores(){const a=state.actions,c=state.checkins,g=state.goals,execution=a.length?a.filter(x=>x.status==='done').length/a.length*100:0,consistency=Math.min(100,c.length/20*100),progress=g.length?g.reduce((s,x)=>s+(x.progress||0),0)/g.length:0,recent=c.slice(0,14),ratio=k=>recent.length?recent.filter(x=>x[k]).length/recent.length*100:0,avg=k=>{const xs=recent.map(x=>Number(x[k])).filter(n=>n>0);return xs.length?xs.reduce((x,y)=>x+y,0)/xs.length:0};const habits={spiritual:ratio('spiritual_practice'),body:ratio('workout'),financial:ratio('finance_habit'),mental:recent.length?Math.max(0,Math.min(100,((((avg('mood')+avg('energy')+avg('sleep_quality')+avg('focus'))/4)+(10-avg('stress')))/2)*10)):0};const pillars={};PKEYS.forEach(p=>{const pa=a.filter(x=>x.pillar===p),pg=g.filter(x=>x.pillar===p),pe=pa.length?pa.filter(x=>x.status==='done').length/pa.length*100:execution,pp=pg.length?pg.reduce((s,x)=>s+(x.progress||0),0)/pg.length:0;pillars[p]=Math.round(Math.max(0,Math.min(100,.45*pe+.3*habits[p]+.25*pp)))});const vals=PKEYS.map(p=>pillars[p]),min=Math.min(...vals),max=Math.max(...vals),bottleneck=PKEYS[vals.indexOf(min)],overall=Math.round(Math.max(0,Math.min(100,vals.reduce((x,y)=>x+y,0)/4*.8+consistency*.1+progress*.1)));return{overall,pillars,execution:Math.round(execution),consistency:Math.round(consistency),progress:Math.round(progress),bottleneck,imbalance:max-min}}
async function saveScore(){const s=state.scores;if(!s)return;await sb.from('future_me_score_snapshots').upsert({user_id:user.id,snapshot_date:new Date().toISOString().slice(0,10),overall:s.overall,spiritual:s.pillars.spiritual,mental:s.pillars.mental,body:s.pillars.body,financial:s.pillars.financial},{onConflict:'user_id,snapshot_date'})}
function renderMenu(){const html=pages().map(([k,n])=>`<button class="${k===current?'on':''}" onclick="go('${k}')">${n}</button>`).join('');menu.innerHTML=html;mobileMenu.innerHTML=html;const bn=[['dashboard','⌂','Início'],['pillars','◉','Pilares'],['mentor','✦','Mentor'],['plan','✓','Plano'],['profile','☰','Mais']];bottomNav.innerHTML=bn.map(([k,i,n])=>`<button class="${current===k?'on':''}" onclick="go('${k}')"><b>${i}</b>${n}</button>`).join('')}
function go(p){if(!pages().some(x=>x[0]===p))p='dashboard';current=p;location.hash=p;renderMenu();render();window.scrollTo({top:0,behavior:'smooth'})}
function render(){const v=$id('view');if(current==='dashboard')renderDashboard(v);else if(current==='pillars')renderPillars(v);else if(current==='mentor')renderMentor(v);else if(current==='vision')renderVision(v);else if(current==='plan')renderPlan(v);else if(current==='checkin')renderCheckin(v);else if(current==='review')renderReview(v);else if(current==='missions')renderMissions(v);else if(current==='declarations')renderDeclarations(v);else if(current==='letter')renderLetter(v);else if(current==='profile')renderProfile(v);else if(current==='plans')renderPlans(v);else if(current==='admin')renderAdmin(v)}
(async()=>{const{data}=await sb.auth.getSession();if(data.session)await boot(data.session);sb.auth.onAuthStateChange((ev,s)=>{if(ev==='SIGNED_IN'&&s&&!session)boot(s);if(ev==='SIGNED_OUT'){session=user=profile=null}})})();